---
# install shadowsocks in docker

- name: install shadowsocks
  hosts: all
  #remote_user: ubuntu
  #become: True
  remote_user: root
  gather_facts: False
  vars:
    ss_version: 3.0.6
  vars_files:
    - vars/password.yml

  pre_tasks:
    - name: install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

  tasks:

    - name: install dependence
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - python-pip
        - python-setuptools
        - docker.io

    - name: install docker-py
      pip: name=docker-py state=present

    - name: start ss
      docker_container:
        name: shadowsocks
        image: 'easypi/shadowsocks-libev:{{ ss_version }}'
        network_mode: host
        env:
          METHOD: aes-256-cfb
          PASSWORD: "{{ ss_password }}"
        restart_policy: always
        state: started
